#!/bin/sh

ldap_filter() {
  PATTERN="(cn|dn|objectClass|distinguishedName|instanceType|whenCreated|whenChanged|uSNCreated|uSNChanged|name|objectGUID|userAccountControl|badPwdCount|codePage|countryCode|badPasswordTime|lastLogoff|lastLogon|pwdLastSet|primaryGroupID|objectSid|accountExpires|logonCount|sAMAccountName|sAMAccountType|userPrincipalName|objectCategory|dSCorePropagationData|sn|memberOf|displayName|logonHours|givenName|isCriticalSystemObject|ref|member|dnsRecord|groupType|scriptPath|lastLogonTimestamp|subRefs|wellKnownObjects|showInAdvancedViewOnly|systemFlags|ipsecName|ipsecID|ipsecDataType|ipsecData|ipsecOwnersReference|msDS-SupportedEncryptionTypes|gPLink|lastSetTime|priorSetTime):"
  grep -v -E "$PATTERN" "$1"
}

# https://0xdf.gitlab.io/2019/06/01/htb-sizzle.html
smb_test_shares() {
  AUTH_FILE="/tmp/.auth_smb"
  FLAGS=""
  if [ $# -eq 3 ]
  then
    echo "username = $2" > $AUTH_FILE
    echo "password = $3" >> $AUTH_FILE
    FLAGS="-A $AUTH_FILE"
  else
    FLAGS="-N"
  fi
  TMP_FILE="/tmp/.test_smb"
  echo "Testing SMB at $1"
  smbclient "$FLAGS" -g -L "$1" 2> /dev/null | tee "$TMP_FILE"
  if grep -q "Disk" "$TMP_FILE";
  then
    grep "Disk" "$TMP_FILE" | sed 's/Disk|\(*.\)|.*/\1/' | while read -r share;
    do echo "======${share}======";
      smbclient "$FLAGS" -c dir "//$1/${share}" ;
      echo;
    done
  else
    echo "Could not find 'Disks' in the share, check manually"
  fi

  rm "$AUTH_FILE"
  rm "$TMP_FILE"
}

smb_test_writable() {
  TMP_NAME="potato"
  find "$1" -type d | while read -r directory ; do
    touch "${directory}/$TMP_NAME" 2>/dev/null && {
      echo "${directory} - file writable";
      rm "${directory}/$TMP_NAME"; 
    }
    mkdir "${directory}/$TMP_NAME" 2>/dev/null && { 
      echo "${directory} - directory writable";
      rmdir "${directory}/$TMP_NAME";
    }
  done
}

