#!/bin/sh

ldap_filter() {
  PATTERN="(cn|dn|objectClass|distinguishedName|instanceType|whenCreated|whenChanged|uSNCreated|uSNChanged|name|objectGUID|userAccountControl|badPwdCount|codePage|countryCode|badPasswordTime|lastLogoff|lastLogon|pwdLastSet|primaryGroupID|objectSid|accountExpires|logonCount|sAMAccountName|sAMAccountType|userPrincipalName|objectCategory|dSCorePropagationData|sn|memberOf|displayNAme|logonHours|givenName|isCriticalSytemObject):"
  grep -v -E $PATTERN "$1"
}

# https://0xdf.gitlab.io/2019/06/01/htb-sizzle.html
smb_test_shares() {
  TMP_FILE="/tmp/.test_smb"
  echo "Testing SMB at $1"
  smbclient -N -L "\\\\$1" 2> /dev/null | tee "$TMP_FILE"
  if grep -q "Disk" "$TMP_FILE";
  then
    grep "Disk" "$TMP_FILE" | sed 's/^\s*\(.*\)\s*Disk.*/\1/' | while read -r share;
    do echo "======${share}======";
      smbclient -N "//$1/${share}" -c dir;
      echo;
    done
  else
    echo "\e[32mCould not find 'Disks' in the share, check manually\e[0m"
  fi

  rm "$TMP_FILE"
}

smb_test_writable() {
  TMP_NAME="potato"
  find "$1" -type d | while read -r directory ; do
    touch "${directory}/$TMP_NAME" 2>/dev/null && {
      echo "${directory} - file writable";
      rm "${directory}/$TMP_NAME"; 
    }
    mkdir "${directory}/$TMP_NAME" 2>/dev/null && { 
      echo "${directory} - directory writable";
      rmdir "${directory}/$TMP_NAME";
    }
  done
}

