on:
  push:
    branches:
      - main

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}
          
      - name: Checkout Github repo
        uses: actions/checkout@v3
    
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: "new_machine winenum"
